"""Add composite indexes for production queries

Revision ID: 3064df18fef9
Revises: 2347281f9f7d
Create Date: 2026-08-26 22:49:18.427669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3064df18fef9'
down_revision: Union[str, None] = '2347281f9f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alloc_house_term', 'allocations', ['house', 'ls_term'], unique=False)
    op.create_index('ix_alloc_mp_house_term', 'allocations', ['mp_id', 'house', 'ls_term'], unique=False)
    op.create_index('ix_exp_house_term', 'expenditures', ['house', 'ls_term'], unique=False)
    op.create_index('ix_exp_house_term_state', 'expenditures', ['house', 'ls_term', 'state'], unique=False)
    op.create_index('ix_exp_mp_house_term', 'expenditures', ['mp_id', 'house', 'ls_term'], unique=False)
    op.create_index('ix_exp_work_id', 'expenditures', ['work_id'], unique=False)
    op.create_index('ix_mp_house_state', 'mps', ['house', 'state'], unique=False)
    op.create_index('ix_work_house_term', 'works', ['house', 'ls_term'], unique=False)
    op.create_index('ix_work_house_term_state', 'works', ['house', 'ls_term', 'state'], unique=False)
    op.create_index('ix_work_mp_house_term', 'works', ['mp_id', 'house', 'ls_term'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_mp_house_term', table_name='works')
    op.drop_index('ix_work_house_term_state', table_name='works')
    op.drop_index('ix_work_house_term', table_name='works')
    op.drop_index('ix_mp_house_state', table_name='mps')
    op.drop_index('ix_exp_work_id', table_name='expenditures')
    op.drop_index('ix_exp_mp_house_term', table_name='expenditures')
    op.drop_index('ix_exp_house_term_state', table_name='expenditures')
    op.drop_index('ix_exp_house_term', table_name='expenditures')
    op.drop_index('ix_alloc_mp_house_term', table_name='allocations')
    op.drop_index('ix_alloc_house_term', table_name='allocations')
    # ### end Alembic commands ###
