"""Initial schema

Revision ID: 9bf35fc6912a
Revises: 
Create Date: 2026-08-27 12:11:37.299138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf35fc6912a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mps',
    sa.Column('mp_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('entity_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('mp_id'),
    sa.UniqueConstraint('entity_key')
    )
    op.create_index('ix_mp_house_state', 'mps', ['house', 'state'], unique=False)
    op.create_index(op.f('ix_mps_house'), 'mps', ['house'], unique=False)
    op.create_index(op.f('ix_mps_name'), 'mps', ['name'], unique=False)
    op.create_index(op.f('ix_mps_state'), 'mps', ['state'], unique=False)
    op.create_table('sync_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house', sa.String(length=20), nullable=True),
    sa.Column('ls_term', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('sync_duration_secs', sa.Float(), nullable=True),
    sa.Column('data_quality_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_datasets', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_metadata_house'), 'sync_metadata', ['house'], unique=False)
    op.create_table('agent_findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('mp_id', sa.String(length=16), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.mp_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_agent_findings_agent_name'), 'agent_findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_findings_mp_id'), 'agent_findings', ['mp_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_severity'), 'agent_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_agent_findings_work_id'), 'agent_findings', ['work_id'], unique=False)
    op.create_table('allocations',
    sa.Column('allocation_id', sa.String(length=36), nullable=False),
    sa.Column('mp_id', sa.String(length=16), nullable=True),
    sa.Column('mp_name', sa.String(length=255), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('ls_term', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.String(length=30), nullable=False),
    sa.Column('source_combo', sa.String(length=30), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.mp_id'], ),
    sa.PrimaryKeyConstraint('allocation_id'),
    sa.UniqueConstraint('house', 'ls_term', 'mp_name', 'constituency', name='uq_allocation_scope')
    )
    op.create_index('ix_alloc_house_term', 'allocations', ['house', 'ls_term'], unique=False)
    op.create_index('ix_alloc_mp_house_term', 'allocations', ['mp_id', 'house', 'ls_term'], unique=False)
    op.create_index(op.f('ix_allocations_house'), 'allocations', ['house'], unique=False)
    op.create_index(op.f('ix_allocations_ls_term'), 'allocations', ['ls_term'], unique=False)
    op.create_index(op.f('ix_allocations_mp_id'), 'allocations', ['mp_id'], unique=False)
    op.create_index(op.f('ix_allocations_mp_name'), 'allocations', ['mp_name'], unique=False)
    op.create_index(op.f('ix_allocations_state'), 'allocations', ['state'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.String(length=16), nullable=True),
    sa.Column('mp_name', sa.String(length=255), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('ls_term', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('work_category', sa.String(length=255), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('implementing_agency', sa.String(length=255), nullable=True),
    sa.Column('recommendation_date', sa.String(length=10), nullable=True),
    sa.Column('recommended_amount', sa.Float(), nullable=True),
    sa.Column('completion_date', sa.String(length=10), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('work_status', sa.String(length=20), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.String(length=30), nullable=False),
    sa.Column('source_combo', sa.String(length=30), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.mp_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house', 'ls_term', 'state', 'work_id', name='uq_work_scope')
    )
    op.create_index('ix_work_house_term', 'works', ['house', 'ls_term'], unique=False)
    op.create_index('ix_work_house_term_state', 'works', ['house', 'ls_term', 'state'], unique=False)
    op.create_index('ix_work_mp_house_term', 'works', ['mp_id', 'house', 'ls_term'], unique=False)
    op.create_index(op.f('ix_works_constituency'), 'works', ['constituency'], unique=False)
    op.create_index(op.f('ix_works_house'), 'works', ['house'], unique=False)
    op.create_index(op.f('ix_works_ls_term'), 'works', ['ls_term'], unique=False)
    op.create_index(op.f('ix_works_mp_id'), 'works', ['mp_id'], unique=False)
    op.create_index(op.f('ix_works_mp_name'), 'works', ['mp_name'], unique=False)
    op.create_index(op.f('ix_works_state'), 'works', ['state'], unique=False)
    op.create_index(op.f('ix_works_work_id'), 'works', ['work_id'], unique=False)
    op.create_index(op.f('ix_works_work_status'), 'works', ['work_status'], unique=False)
    op.create_table('expenditures',
    sa.Column('expenditure_id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('mp_id', sa.String(length=16), nullable=True),
    sa.Column('mp_name', sa.String(length=255), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('ls_term', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('implementing_agency', sa.String(length=255), nullable=True),
    sa.Column('expenditure_date', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=True),
    sa.Column('expenditure_amount', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.String(length=30), nullable=False),
    sa.Column('source_combo', sa.String(length=30), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['house', 'ls_term', 'state', 'work_id'], ['works.house', 'works.ls_term', 'works.state', 'works.work_id'], name='fk_expenditure_work'),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.mp_id'], ),
    sa.PrimaryKeyConstraint('expenditure_id')
    )
    op.create_index('ix_exp_house_term', 'expenditures', ['house', 'ls_term'], unique=False)
    op.create_index('ix_exp_house_term_state', 'expenditures', ['house', 'ls_term', 'state'], unique=False)
    op.create_index('ix_exp_mp_house_term', 'expenditures', ['mp_id', 'house', 'ls_term'], unique=False)
    op.create_index('ix_exp_work_id', 'expenditures', ['work_id'], unique=False)
    op.create_index(op.f('ix_expenditures_house'), 'expenditures', ['house'], unique=False)
    op.create_index(op.f('ix_expenditures_ls_term'), 'expenditures', ['ls_term'], unique=False)
    op.create_index(op.f('ix_expenditures_mp_id'), 'expenditures', ['mp_id'], unique=False)
    op.create_index(op.f('ix_expenditures_mp_name'), 'expenditures', ['mp_name'], unique=False)
    op.create_index(op.f('ix_expenditures_payment_status'), 'expenditures', ['payment_status'], unique=False)
    op.create_index(op.f('ix_expenditures_state'), 'expenditures', ['state'], unique=False)
    op.create_index(op.f('ix_expenditures_work_id'), 'expenditures', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenditures_work_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_state'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_payment_status'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_mp_name'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_mp_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_ls_term'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_house'), table_name='expenditures')
    op.drop_index('ix_exp_work_id', table_name='expenditures')
    op.drop_index('ix_exp_mp_house_term', table_name='expenditures')
    op.drop_index('ix_exp_house_term_state', table_name='expenditures')
    op.drop_index('ix_exp_house_term', table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_works_work_status'), table_name='works')
    op.drop_index(op.f('ix_works_work_id'), table_name='works')
    op.drop_index(op.f('ix_works_state'), table_name='works')
    op.drop_index(op.f('ix_works_mp_name'), table_name='works')
    op.drop_index(op.f('ix_works_mp_id'), table_name='works')
    op.drop_index(op.f('ix_works_ls_term'), table_name='works')
    op.drop_index(op.f('ix_works_house'), table_name='works')
    op.drop_index(op.f('ix_works_constituency'), table_name='works')
    op.drop_index('ix_work_mp_house_term', table_name='works')
    op.drop_index('ix_work_house_term_state', table_name='works')
    op.drop_index('ix_work_house_term', table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_allocations_state'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_mp_name'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_mp_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_ls_term'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_house'), table_name='allocations')
    op.drop_index('ix_alloc_mp_house_term', table_name='allocations')
    op.drop_index('ix_alloc_house_term', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_agent_findings_work_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_severity'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_mp_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent_name'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_sync_metadata_house'), table_name='sync_metadata')
    op.drop_table('sync_metadata')
    op.drop_index(op.f('ix_mps_state'), table_name='mps')
    op.drop_index(op.f('ix_mps_name'), table_name='mps')
    op.drop_index(op.f('ix_mps_house'), table_name='mps')
    op.drop_index('ix_mp_house_state', table_name='mps')
    op.drop_table('mps')
    # ### end Alembic commands ###
