/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as RegionalInsightsRouteImport } from './routes/regional-insights'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as MpsIndexRouteImport } from './routes/mps/index'
import { Route as MpsIdRouteImport } from './routes/mps/$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalInsightsRoute = RegionalInsightsRouteImport.update({
  id: '/regional-insights',
  path: '/regional-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const MpsIndexRoute = MpsIndexRouteImport.update({
  id: '/mps/',
  path: '/mps/',
  getParentRoute: () => rootRouteImport,
} as any)
const MpsIdRoute = MpsIdRouteImport.update({
  id: '/mps/$id',
  path: '/mps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/regional-insights': typeof RegionalInsightsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/mps/$id': typeof MpsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/mps/': typeof MpsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/regional-insights': typeof RegionalInsightsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/mps/$id': typeof MpsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/mps': typeof MpsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/regional-insights': typeof RegionalInsightsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/mps/$id': typeof MpsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/mps/': typeof MpsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/data-sources'
    | '/how-it-works'
    | '/regional-insights'
    | '/settings'
    | '/system-status'
    | '/mps/$id'
    | '/projects/$id'
    | '/mps/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/data-sources'
    | '/how-it-works'
    | '/regional-insights'
    | '/settings'
    | '/system-status'
    | '/mps/$id'
    | '/projects/$id'
    | '/mps'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/data-sources'
    | '/how-it-works'
    | '/regional-insights'
    | '/settings'
    | '/system-status'
    | '/mps/$id'
    | '/projects/$id'
    | '/mps/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RegionalInsightsRoute: typeof RegionalInsightsRoute
  SettingsRoute: typeof SettingsRoute
  SystemStatusRoute: typeof SystemStatusRoute
  MpsIdRoute: typeof MpsIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  MpsIndexRoute: typeof MpsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-insights': {
      id: '/regional-insights'
      path: '/regional-insights'
      fullPath: '/regional-insights'
      preLoaderRoute: typeof RegionalInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mps/': {
      id: '/mps/'
      path: '/mps'
      fullPath: '/mps/'
      preLoaderRoute: typeof MpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mps/$id': {
      id: '/mps/$id'
      path: '/mps/$id'
      fullPath: '/mps/$id'
      preLoaderRoute: typeof MpsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  HowItWorksRoute: HowItWorksRoute,
  RegionalInsightsRoute: RegionalInsightsRoute,
  SettingsRoute: SettingsRoute,
  SystemStatusRoute: SystemStatusRoute,
  MpsIdRoute: MpsIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  MpsIndexRoute: MpsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
